# Generated by Django 5.2.1 on 2025-05-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("official_name", models.CharField(blank=True, max_length=150)),
                ("region", models.CharField(max_length=100)),
                ("subregion", models.CharField(blank=True, max_length=100)),
                ("independent", models.BooleanField(null=True)),
                ("capital", models.CharField(blank=True, max_length=100)),
                ("capital_lat", models.FloatField(blank=True, null=True)),
                ("capital_lon", models.FloatField(blank=True, null=True)),
                ("google_maps", models.URLField(blank=True)),
                ("open_street_map", models.URLField(blank=True)),
                ("flag_png", models.URLField(blank=True)),
                ("flag_svg", models.URLField(blank=True)),
                ("flag_alt", models.CharField(blank=True, max_length=255)),
                ("coat_of_arms_png", models.URLField(blank=True)),
                ("coat_of_arms_svg", models.URLField(blank=True)),
                ("borders", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="NameRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("request_count", models.IntegerField(default=1)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NameCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("probability", models.FloatField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_associations",
                        to="api.country",
                    ),
                ),
                (
                    "name_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_associations",
                        to="api.namerequest",
                    ),
                ),
            ],
        ),
    ]
